# Generated by Django 6.1.1 on 2026-09-23 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='assigned_user',
            new_name='member',
        ),
        migrations.RenameField(
            model_name='board',
            old_name='name',
            new_name='titel',
        ),
    ]
