# Generated by Django 6.1.1 on 2026-10-02 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0008_alter_task_prio_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='text',
            new_name='content',
        ),
    ]
