# Generated by Django 6.1.1 on 2026-09-23 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_rename_assigned_user_board_member_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='titel',
            new_name='title',
        ),
    ]
