# Generated by Django 6.1.1 on 2026-09-23 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_rename_titel_board_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='member',
            new_name='members',
        ),
    ]
